jupytercalpoly/jupyterlab-comments

src/commentformat.ts
src/comments.ts
src/index.ts
src/utils.ts
src/widget.tsx

- Comments names are now based on the JupyterLab-generated "Anonymous [moon]" format.
- Comment widgets take an `Awareness` as part of the constructor
- `IComment` objects have an identity field of type `IIdentity`

added JupyterLab-generated identity to comments

---

src/commentformat.ts
src/comments.ts
src/utils.ts
src/widget.tsx
style/base.css

Addresses Issue #27
- Added a circular "profile picture" stand-in in the user's JupyterLab-assigned color.
- Big style changes! Still not entirely in line with the vision of #26 but much better.
- Replaced reply textarea with a contentEditable div.
- Fixed a bug causing an extra newline after a reply.

added 'profile pic'; style changes

---

MANIFEST.in
Press_Release.md
src/comments.ts
src/index.ts
src/panel.ts
src/widget.tsx
style/base.css

Addresses Issue #18 
A bit of a chunky PR!
- Added a focus tracker for `CommentWidget`s. Allows for commands that delete/edit/etc the current comment widget.
- Made focused comment widgets have a blue border.
- Added a dropdown menu to comment widgets. Currently only allows for deleting the comment, but it should be easy to add entries.
- Removed buttons for lean, sexy comment widgets.

Dropdown menu and focus tracker

---

src/comments.ts

Addressed bug from (#38) by blocking off edits to empty strings and preventing addition of comments with empty strings.

Prevent empty entries for comments and replies

---

src/comments.ts
src/widget.tsx
style/base.css

Added in changes to the edit box :
I'm not too sure if we should add in the profile pic or anything else since it might clutter the reply.
Will merge after resolving reply box contents.

Improved reply and edit box

---

src/index.ts
src/widget.tsx
style/base.css

This PR implements core changes/simplifications to how comment widgets are rendered, as well as some general usability/quality-of-life improvements.
The single huge `render()` function of comments has been broken up into several smaller react components and wrapped in a `<UseSignal/>` component, which allows for easier re-rendering. In addition, the `handleEvent()` CommentWidget method handles all click and keydown events across the widget. Events are dispatched according to the area of the widget they occur on, which is determined by the `CommentWidget.getEventArea()` function. Hopefully these changes make it easier to add elements and handle events without a whole mess of hooks and nested functions.
Some QOL improvements:
- Ellipses/dropdown only visible when the comment widget is …

Refactored react widget + quality-of-life improvements

---

src/widget.tsx

Implemented custom div and span elements called Jdiv and Jspan that allow for safe custom react props to be passed to the element.
This is essentially a way to bypass the typescript's default behavior of throwing a error when passing custom react props.

Remove the compiler directives 

---

src/index.ts
src/panel.ts

Addresses Issue #24 
The comment panel now displays comments at the document level instead of the cell level. The panel is updated whenever the active document changes and clicking a cell now scrolls the first comment on that cell into view.
This PR also adds a `revealed` signal in the panel widget.

Unified comments panel

---

src/comments.ts
src/index.ts
src/panel.ts
src/widget.tsx
style/base.css

Sort of addresses Issue #34 ?
Includes commits from PR #43 
Added some styling changes to make comment widgets more compact. Also fixed a bug where editing a comment's text to be empty leaves the body empty until a re-render.
A comparison of the old vs the new styling: (new left, old right)

Compact widgets

---

src/commentformat.ts
src/widget.tsx
style/base.css

Addresses Issue #20 
Added a comment preview area. Currently just prints the text of the comment but will be modified to show the contents of a text selection.
Also fixed a dark mode display bug.

started work on comment preview

---

Press_Release.md
package.json
src/commentformat.ts
src/comments.ts
src/index.ts
src/panel.ts
src/utils.ts
src/widget.tsx
style/base.css
yarn.lock

Comments now rely on shared model metadata instead of IModelDB metadata. This means remote changes can be listened for and the panel updated accordingly. It also means comments are now updated consistently in real-time between collaborators!

Fixed RTC for comments

---

src/architecture.ts
src/commentformat.ts
src/comments.ts
src/factory.ts
src/index.ts
src/panel.ts
src/registry.ts
src/widget.tsx

Started work on Issue #63 
- Formally distinguished replies from comments (replies have no replies or target and always have the type 'reply').
- Made the comment format in `commentformat.ts` more hierarchical. 
- Removed comment input from comment panel.
- Created interface for `CommentPanel`
- Moved `ICommentPanel` into a separate plugin.
- Created a `CommentFactory` class for describing how to create a comment of a specific type. I might want to make this an abstract class and make each specific kind of factory a subclass.
- Created a `CommentRegistry` to store and retrieve comment factories.
- Created a plugin for `ICommentRegistry`.
- Changed current notebook implementation to use comment factories in most places.
Also created `architecture.ts` describing the future of the general …

Started work on general comments architecture

---

src/architecture.ts
src/commentformat.ts
src/comments.ts
src/factory.ts
src/index.ts
src/model.ts
src/panel.ts
src/registry.ts
src/widget.tsx

Starts to address Issue #74 
Also includes commits from PR #72 
A default implementation of `ICommentModel`. Implements methods for adding, deleting, editing, and retrieving comments and replies, as well as serializing/deserializing the model.
TODO: Emit a meaningful changed signal when the comments change; initialize the ydoc in the constructor given a source file path.

Initial work on comment file model

---

src/index.ts
src/panel.ts

Addresses Issue #87 
Also has the (fortunate?) side effect of revealing the comment panel when opening/switching to a document with comments.

made adding a comment reveal the comment panel

---

src/button.ts
src/factory.ts
src/index.ts
src/model.ts
src/panel.ts
src/widget.tsx

Before, every change to a comment widget would involve disposing of and re-creating every comment widget in the panel. This was inefficient and I believed it was causing an issue with rendering text selections. Unfortunately, this did not fix the text selection issue, but it did make rendering comments faster.
- Incremental re-rendering of comments.
- Fixed bug where "+ comment" button wouldn't move when scrolling.
- Mock comment widget.
- Comment model emits a `changed` signal with the change delta.
- `getComment` and `getReply` methods of the model return an object with the target and the target's index.
- Adding a comment now opens an empty "mock comment" in the comment panel that the user fills in. This replaces the previous pop-up dialogue.

Incremental comment updates and mock comments

---

src/index.ts
src/panel.ts

Ugly pre-demo patch to prevent comments breaking when the source file is renamed or moved. Doesn't cause the name to update in the panel header but fine for now.

change comment file name when source file renamed

---

src/factory.ts
src/index.ts
src/panel.ts
src/widget.tsx
style/base.css

Addresses Issue #115
Highlighting text in a notebook now causes the "+ comment" button to appear as expected. The button also appears aligned with the vertical middle of the text selection as it does for text files.
Adding a comment also reveals the side panel and scrolls to the mock comment as intended.
In addition, this PR introduces some small styling changes.
- Cursor is now the "pointer" cursor when hovering over the comment expander.
- Comment expander circle border is blue when comment is focused.
- Slight horizontal margin decrease for body text.
- Slight comment body text size decrease.
- Comment nametag is now less slightly less bold.

Notebook button bug fix

---

src/widget.tsx
style/base.css

Addressed the issue #104 by adding in a custom CSS selector. Also changed the flow of rendering to happen every single time the comment/reply gets rendered in `JCComment` and `JCReply` to fix a bug where the reply's formatting disappears when its comment widget gets focus.

Fix chin bug from markdown rendering in comments and replies

---

src/model.ts
src/panel.ts
src/panelHeaderWidget.tsx
style/base.css

Addresses issue #126 
Removes the unused dummy buttons on the comment panel and adds working save and refresh buttons. Also adds the path to the comment file on mouseover of the source file title.
Still needs some sort of visual feedback that the save button was pressed--maybe a dot in the panel that indicates the "dirty" status that's cleared by a save?
EDIT: Added dirty indicator.

added save/refresh buttons to comment panel header

---

README.md
src/factory.ts
src/index.ts
src/model.ts
src/panel.ts
src/panelHeaderWidget.tsx
src/widget.tsx

Addresses issues #122 and #111
- Made text selections relative. They now expand/shrink to accommodate changes to the source text.
- Text selections are now in the user's color and have the comment text in the tooltip.
- Made some timing fixes to the model loading/saving system.
- Comments are now serialized by the `toJSON` method of their factory.
- Added a "save" option to the comment panel context menu.
- Fixed a bug where creating a new comment file would log a 404 error to the console.
- Fixed a bug where switching documents would cause comments from both documents to be briefly visible.
- Made clicking a comment scroll to the target of that comment.

Relative selections + other improvements

---

src/api/widget.tsx

- Enter/shift enter behavior is now standardized across comments and replies (Enter = newline, Shift + Enter = submit).
- Whitespace comments are not allowed. This also fixes a bug where mock comments would stay mock after submitting them.
- Submit button now works correctly with mock comments.

Submit comment bug fixes
