jupytercalpoly/jupyterlab-comments

MANIFEST.in

updated manifest.in to pass build

updated manifest

---

MANIFEST.in

fixed manifest again to actually fix build

actually fixed MANIFEST.in

---

package.json
src/index.ts
yarn.lock

Added very basic collaborative """"commenting""""" through the `Add Comment` and `Render Comment` context menu items for notebook cells, which simply add and display a message respectively.

added comment proof-of-concept

---

src/commentformat.ts
src/comments.ts

Added the start of a comment schema file (commentformat.ts) and a few utility functions for retrieving/setting comments in metadata.

added comment schema and utility functions

---

binder/environment.yml

updated node and jupyterlab versions in binder

updated binder

---

.eslintrc.js
package.json
src/commentformat.ts
src/comments.ts
src/index.ts
src/widget.tsx
style/base.css
yarn.lock

- Fixed type of 'replies' in `IComment`
- Made `comments.ts` utility functions work on any `IObservableJSON` object.
- Started work on React comment widget. Widgets can be deleted with the 'x' button and a reply box can be revealed by clicking the comment. Still very buggy--deleting a reply isn't visible until 'add reply' box is revealed/hidden or the cell is re-focused.

Started react widget work

---

src/commentformat.ts
src/index.ts
src/panel.ts
style/base.css

Moved functionality to match Jupyter design patterns.
- Removed unused commentformat types
- Moved panel rendering and new comment functionality to the `CommentPanel` class.
- Moved command adding in index.ts to an `addCommands` function.
- Made the new comment dialogue a styled editable div.

Code cleanup

---

src/widget.tsx

Fixed the issue ( #15 ) by handling the filtering within the React widget and useState to communicate to React to rerender the CommentWidget.

Fixed reply deleting bug

---

src/comments.ts
src/widget.tsx

- Simplified the functions that delete comments and replies by passing in only ids
- Handled react mouse events within the widget
- Moved the new functions to the comments.ts file

Refactored deletion system for comments and replies

---

src/widget.tsx

Forgot to remove it in the earlier PR so here it is!

Remove the comment parameter for `onDeleteClick`

---

src/index.ts
src/panel.ts
src/utils.ts
src/widget.tsx
style/base.css

Timestrings are now more minimal and readable
The light text isn't accessible.... but it looks so good 🥴

changed timestring and timestamp formatting

---

src/comments.ts
src/widget.tsx
style/base.css

Editing works from clicking the edit button, the double clicking functionality can be tacked on when we remove the functionality of single click for reply.

Enabled editing for comments and replies

---

Press_Release.md

Added the Press Release file for this JupyterLab Extension.

Add Press Release file

---

README.md
binder/environment.yml
binder/postBuild

added binder config and badge

---

binder/environment.yml

fixed conda-forge typo

---

binder/environment.yml

updated binder channels

---

binder/jupyter_config.json
src/utils.ts

made binder collaborative; added nullish check in getIdentity

---

MANIFEST.in
package.json
src/index.ts
src/panel.ts
src/utils.ts
src/widget.tsx
style/base.css
tsconfig.json
webpack_config.js

Some improvements I made before the first internal Jupyter demo.
- Performance/code  improvements on the text selection comment handlers.
- Clicking on comments scrolls to the cell of the comment
- Added drop shadow and increased spacing between comment threads.

pre-demo improvements

---

.eslintrc.js
src/comments.ts
src/factory.ts
src/index.ts
src/model.ts
src/panel.ts
src/registry.ts
src/widget.tsx

Allowed for easier expand-ability for the comments by creating a abstract factory that specific type of comments can implement.

Abstract factory implementation

---

style/base.css

Added in change based on chloe's recommendation for spacing.

change margins for file name

---

src/widget.tsx
style/base.css

Addressed #33 by adding in collapsible comments. A comment collapses if it contains more than **4 replies**.

Making comment replies collapsible 

---

src/model.ts

Addresses Issue #109 
Work-around to the deletion/re-insertion problem. A more permanent solution probably involves replacing the `IComment` objects with comment models that implement `IComment` and wrap a `Y.Map`, but this is a quick fix for now.

allow updating comments without deleting/re-inserting them

---

src/factory.ts
src/index.ts

* comments on text files are now ordered by start point of the selection (#101)

Text File Comment Order

---

src/utils.ts

* changed the current outline color set for profile icons to [this](https://files.slack.com/files-pri/T148Y6FNV-F02AV6D0YTX/image.png) done by @chloefrerichs

New Icon Colors

---

src/widget.tsx
style/base.css

Address the issue #129. This system doesn't allow for empty comments and replies but the color of the submit button does not change when in a inactive state.

Submit and cancel buttons

---

MANIFEST.in
docs/Makefile
docs/conf.py
docs/developers.md
docs/index.rst
docs/introduction.md
docs/make.bat
docs/users.md

Address the issue in #131  
Added in rudimentary structure for the docs.

Read the docs

---

package.json

version bump (0.1.1)

---

package.json
style/base.css

Added min height to comment body

---

src/api/widget.tsx

Add in reply visible on focus
